### ISSUE TITLE
Made 2 fixes to make it work

### ISSUE THREAD

**Issue by dimmduh** [matt-tekly/webster-docs#1]
1) Invalid json (float 1,323 -> 1.323)
Added CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;  to ComponentInfo.ConvertToValuesJson #62

2) null pointer - ignore missing components
GameObjectSummary.GameObjectSummary #63 -> var components = go.GetComponents<Component>().Where(component => component != null).ToArray();

**Comment by matt-tekly** [comment]
Thanks for pointing these out. I'll release a new version with these changes in the next few days.

**Comment by matt-tekly** [comment]
Updated package is now live in the store. Closing this ticket.
